---
abstract: 'Facilitates the creation and modification of PDF files'
author:
  - 'Phil Perry'
build_requires:
  ExtUtils::MakeMaker: '6.66'
  Test::Exception: '0'
  Test::Memory::Cycle: '1.0'
configure_requires:
  ExtUtils::MakeMaker: '6.66'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: lgpl_2_1
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PDF-Builder
no_index:
  directory:
    - t
    - inc
provides:
  PDF::Builder:
    file: lib/PDF/Builder.pm
    version: v3.027
  PDF::Builder::Annotation:
    file: lib/PDF/Builder/Annotation.pm
  PDF::Builder::Content:
    file: lib/PDF/Builder/Content.pm
  PDF::Builder::Content::Hyphenate_basic:
    file: lib/PDF/Builder/Content/Hyphenate_basic.pm
  PDF::Builder::Content::Text:
    file: lib/PDF/Builder/Content/Text.pm
  PDF::Builder::Docs:
    file: lib/PDF/Builder/Content/Docs.pm
  PDF::Builder::FontManager:
    file: lib/PDF/Builder/FontManager.pm
  PDF::Builder::NamedDestination:
    file: lib/PDF/Builder/NamedDestination.pm
  PDF::Builder::Outline:
    file: lib/PDF/Builder/Outline.pm
  PDF::Builder::Outlines:
    file: lib/PDF/Builder/Outlines.pm
  PDF::Builder::Page:
    file: lib/PDF/Builder/Page.pm
  PDF::Builder::Resource::ColorSpace:
    file: lib/PDF/Builder/Resource/ColorSpace.pm
  PDF::Builder::Resource::Colors:
    file: lib/PDF/Builder/Resource/Colors.pm
  PDF::Builder::Resource::Font:
    file: lib/PDF/Builder/Resource/Font.pm
  PDF::Builder::Resource::PaperSizes:
    file: lib/PDF/Builder/Resource/PaperSizes.pm
  PDF::Builder::Resource::XObject:
    file: lib/PDF/Builder/Resource/XObject.pm
  PDF::Builder::Resource::XObject::Form:
    file: lib/PDF/Builder/Resource/XObject/Form.pm
  PDF::Builder::Resource::XObject::Image:
    file: lib/PDF/Builder/Resource/XObject/Image.pm
  PDF::Builder::ViewerPreferences:
    file: lib/PDF/Builder/ViewerPreferences.pm
#recommends:
#  Graphics::TIFF: '19'
#  HarfBuzz::Shaper: '0.024'
#  Image::PNG::Libpng: '0.57'
#  Text::Markdown: '1.000031'
#  HTML::TreeBuilder: '5.07'
#  Pod::Simple::XHTML: '3.45'
#  SVGPDF: '0.086.2'
requires:
  Compress::Zlib: '1.0'
  Font::TTF: '1.04'
  perl: '5.028000'
resources:
  bugtracker: https://github.com/PhilterPaper/Perl-PDF-Builder/issues
  homepage: https://metacpan.org/pod/PDF::Builder
  repository: git://github.com/PhilterPaper/Perl-PDF-Builder.git
version: '3.027'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
