---
abstract: 'Facilitates the creation and modification of PDF files'
author:
  - 'Phil Perry'
build_requires:
  ExtUtils::MakeMaker: '6.66'
  Test::Exception: '0'
  Test::Memory::Cycle: '1.0'
configure_requires:
  ExtUtils::MakeMaker: '6.66'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: lgpl_2_1
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PDF-Builder
no_index:
  directory:
    - t
    - inc
#recommends:
#  Graphics::TIFF: '19'
#  HarfBuzz::Shaper: '0.024'
#  Image::PNG::Libpng: '0.57'
#  Text::Markdown: '1.000031'
#  HTML::TreeBuilder: '5.07'
requires:
  Compress::Zlib: '1.0'
  Font::TTF: '1.04'
  perl: '5.024000'
resources:
  bugtracker: https://github.com/PhilterPaper/Perl-PDF-Builder/issues
  homepage: https://metacpan.org/pod/PDF::Builder
  repository: git://github.com/PhilterPaper/Perl-PDF-Builder.git
version: '3.025'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
