name: Test
on:
  - push
  - pull_request
jobs:
  full-ubuntu:
    name: Full_Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-add-repository ppa:jeffreyratcliffe/ppa
      - run: sudo apt update
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl ghostscript libgraphics-tiff-perl gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
  nogt:
    name: noGT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl libreadonly-perl ghostscript gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
  nogt_nogs:
    name: noGT_noGS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl libreadonly-perl gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
## currently doesn't work. remove for the time being
# lint:
#   name: Lint
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: github/super-linter@v3
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         FILTER_REGEX_EXCLUDE: Makefile.PL
  basic-windows:
    name: Basic Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cpan Font::TTF GD IO::Compress Test::Exception Test::Memory::Cycle Readonly
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
## currently doesn't work. remove for the time being
# full-windows:
#   name: Full Windows
#   runs-on: windows-latest
#   steps:
#     - uses: actions/checkout@v2
#     - run: choco install imagemagick dejavufonts ghostscript
#     - run: refreshenv
#     - run: |
#         $folders = Get-ChildItem "C:\Program Files\ImageMagick*"
#         foreach ($folder in $folders) {
#             $imfolder = $folder.FullName
#         }
#         $folders = Get-ChildItem "C:\Program Files\gs"
#         foreach ($folder in $folders) {
#             $gsfolder = $folder.FullName
#         }
#         echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;$imfolder;$gsfolder\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
#     - run: magick convert -version
#     - run: gswin64c -v
#     - run: cpan Font::TTF GD IO::Compress Test::Exception Test::Memory::Cycle Graphics::TIFF
#     - run: perl Makefile.PL
#     - run: make test TEST_VERBOSE=1
