name: Test
on:
  - push
  - pull_request
jobs:
  full-ubuntu:
    name: Full_Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-add-repository ppa:jeffreyratcliffe/ppa
      - run: sudo apt update
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl ghostscript libgraphics-tiff-perl gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
  nogt:
    name: noGT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl ghostscript gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
  nogt_nogs:
    name: noGT_noGS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libfont-ttf-perl libgd-perl libio-compress-perl libtest-exception-perl libtest-memory-cycle-perl gsfonts
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1
# lint:
#   name: Lint
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: github/super-linter@v3
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         FILTER_REGEX_EXCLUDE: Makefile.PL
